/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DemoRouteImport } from "./routes/demo";

const IndexLazyRouteImport = createFileRoute("/")();

const DemoRoute = DemoRouteImport.update({
  id: "/demo",
  path: "/demo",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/demo.lazy").then((d) => d.Route));
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/demo": typeof DemoRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/demo": typeof DemoRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexLazyRoute;
  "/demo": typeof DemoRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/demo";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/demo";
  id: "__root__" | "/" | "/demo";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  DemoRoute: typeof DemoRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/demo": {
      id: "/demo";
      path: "/demo";
      fullPath: "/demo";
      preLoaderRoute: typeof DemoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DemoRoute: DemoRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
